os: linux
dist: bionic
language: php

env:
  - COMPOSER_PREFER=default PHP_CS_FIXER_IGNORE_ENV=true
  - COMPOSER_PREFER=lowest PHP_CS_FIXER_IGNORE_ENV=true

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install: "[[ $COMPOSER_PREFER == 'lowest' ]] && composer update --prefer-lowest || composer install"

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/psalm --show-info=true
  - vendor/bin/phpunit --coverage-text
